# Generated by Django 6.0.7 on 2026-07-09 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mockinterview',
            name='company',
        ),
        migrations.RemoveField(
            model_name='mockinterview',
            name='date',
        ),
        migrations.RemoveField(
            model_name='mockinterview',
            name='improvement',
        ),
        migrations.RemoveField(
            model_name='mockinterview',
            name='strengths',
        ),
        migrations.RemoveField(
            model_name='mockinterview',
            name='time',
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='difficulty',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='intermediate', max_length=50),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='feedback',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='questions_and_answers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mockinterview',
            name='type',
            field=models.CharField(choices=[('behavioral', 'Behavioral'), ('technical', 'Technical'), ('case_study', 'Case Study')], default='behavioral', max_length=50),
        ),
        migrations.AlterField(
            model_name='mockinterview',
            name='role',
            field=models.CharField(default='Software Engineer', max_length=255),
        ),
        migrations.AlterField(
            model_name='mockinterview',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='scheduled', max_length=50),
        ),
    ]
