# Generated by Django 6.0.7 on 2026-07-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_usersettings_two_factor_enabled_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('mentor', 'Mentor'), ('employer', 'Employer'), ('admin', 'Admin')], default='student', max_length=20),
        ),
    ]
