# Generated by Django 6.0.7 on 2026-07-09 18:09

import apps.verification.models
import apps.verification.validators
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='document_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\Servepalli Alekhya\\Downloads\\ElevateHer Education, FinTech & Career Empowerment\\backend\\private_media'), upload_to=apps.verification.models.secure_upload_path, validators=[apps.verification.models.validate_file_size, apps.verification.validators.validate_file_type]),
        ),
        migrations.AlterField(
            model_name='verification',
            name='id_number_masked',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='id_type',
            field=models.CharField(blank=True, choices=[('aadhaar', 'Aadhaar Card'), ('passport', 'Passport'), ('driving_licence', 'Driving Licence'), ('voter_id', 'Voter ID'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
