# Generated by Django 6.0.7 on 2026-07-10 11:11

import apps.verification.models
import apps.verification.validators
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verification', '0002_alter_verification_document_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='document_file',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='D:\\ElevateHer Education, FinTech & Career Empowerment\\starcoders-v2v\\backend\\private_media'), upload_to=apps.verification.models.secure_upload_path, validators=[apps.verification.models.validate_file_size, apps.verification.validators.validate_file_type]),
        ),
    ]
