# Generated by Django 6.0.7 on 2026-07-09 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialgoal',
            name='category',
            field=models.CharField(choices=[('emergency', 'Emergency Fund'), ('investment', 'Investment'), ('debt', 'Debt Payoff'), ('purchase', 'Big Purchase'), ('education', 'Education'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.CreateModel(
            name='GoalContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='finance.financialgoal')),
            ],
        ),
    ]
