# Generated by Django 6.0.7 on 2026-07-09 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='apply_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
